import {
  View, Text, ScrollView, TouchableOpacity,
  StyleSheet, RefreshControl, ActivityIndicator,
  Linking, Alert,
} from "react-native";
import { useState, useEffect, useCallback } from "react";
import api from "../../lib/api";

const severityConfig = {
  contraindicated: {
    color: "#7f1d1d", bg: "#fff1f2", border: "#fecdd3",
    badge: "#fecdd3", badgeText: "#7f1d1d", icon: "🚫", label: "Contraindicated",
  },
  major: {
    color: "#7f1d1d", bg: "#fff1f2", border: "#fecdd3",
    badge: "#fecdd3", badgeText: "#7f1d1d", icon: "⛔", label: "Major",
  },
  moderate: {
    color: "#78350f", bg: "#fffbeb", border: "#fde68a",
    badge: "#fde68a", badgeText: "#78350f", icon: "⚠️", label: "Moderate",
  },
  minor: {
    color: "#1e3a5f", bg: "#eff6ff", border: "#bfdbfe",
    badge: "#bfdbfe", badgeText: "#1e3a5f", icon: "ℹ️", label: "Minor",
  },
};

export default function InteractionsScreen({ navigation }) {
  const [alerts, setAlerts]       = useState([]);
  const [loading, setLoading]     = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [expanded, setExpanded]   = useState(null);

  const fetchAlerts = useCallback(async () => {
    try {
      const { data } = await api.get("/interactions");
      setAlerts(data);
    } catch (err) {
      console.error("Failed to load interactions", err);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => { fetchAlerts(); }, [fetchAlerts]);

  const onRefresh = () => { setRefreshing(true); fetchAlerts(); };

  const toggleExpand = (id) => {
    setExpanded((prev) => prev === id ? null : id);
  };

  const callEmergency = () => {
    Alert.alert(
      "Call Emergency Services",
      "Are you sure you want to call emergency services?",
      [
        { text: "Cancel", style: "cancel" },
        { text: "Call now", style: "destructive", onPress: () => Linking.openURL("tel:911") },
      ]
    );
  };

  const unacknowledged = alerts.filter((a) => !a.acknowledged);
  const acknowledged   = alerts.filter((a) => a.acknowledged);

  if (loading) return (
    <View style={styles.centered}>
      <ActivityIndicator size="large" color="#1a3a5c" />
    </View>
  );

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.content}
      refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} />}
    >
      {/* Header */}
      <Text style={styles.pageTitle}>Drug Interactions</Text>
      <Text style={styles.pageSubtitle}>
        AI-detected interactions between your medications
      </Text>

      {/* Emergency Banner */}
      <View style={styles.emergencyBanner}>
        <Text style={styles.emergencyText}>
          🚨 If you are experiencing a medical emergency, call emergency
          services immediately. Do not wait.
        </Text>
        <TouchableOpacity style={styles.emergencyBtn} onPress={callEmergency}>
          <Text style={styles.emergencyBtnText}>Call 911</Text>
        </TouchableOpacity>
      </View>

      {/* Disclaimer */}
      <View style={styles.disclaimer}>
        <Text style={styles.disclaimerText}>
          ⚕️ These alerts are generated by an AI system for decision-support
          only. Do not change or stop your medications without consulting your
          healthcare provider.
        </Text>
      </View>

      {/* No Alerts */}
      {alerts.length === 0 && (
        <View style={styles.emptyBox}>
          <Text style={styles.emptyEmoji}>✅</Text>
          <Text style={styles.emptyTitle}>No interactions detected</Text>
          <Text style={styles.emptyText}>
            Our system has not detected any potential drug interactions
            with your current medications.
          </Text>
        </View>
      )}

      {/* Unacknowledged Alerts */}
      {unacknowledged.length > 0 && (
        <>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionTitle}>Active alerts</Text>
            <View style={styles.countBadge}>
              <Text style={styles.countBadgeText}>{unacknowledged.length}</Text>
            </View>
          </View>

          {unacknowledged.map((alert) => {
            const s = severityConfig[alert.severity] || severityConfig.minor;
            const isExpanded = expanded === alert._id;

            return (
              <TouchableOpacity
                key={alert._id}
                onPress={() => toggleExpand(alert._id)}
                activeOpacity={0.8}
                style={[styles.alertCard, { backgroundColor: s.bg, borderColor: s.border }]}
              >
                {/* Card Header */}
                <View style={styles.alertHeader}>
                  <Text style={styles.alertIcon}>{s.icon}</Text>
                  <View style={styles.alertHeaderText}>
                    <View style={styles.alertTitleRow}>
                      <View style={[styles.severityBadge, { backgroundColor: s.badge }]}>
                        <Text style={[styles.severityBadgeText, { color: s.badgeText }]}>
                          {s.label}
                        </Text>
                      </View>
                      <Text style={styles.alertDate}>
                        {new Date(alert.createdAt).toLocaleDateString("en-US", {
                          month: "short", day: "numeric",
                        })}
                      </Text>
                    </View>
                    <Text style={[styles.alertDescription, { color: s.color }]} numberOfLines={isExpanded ? undefined : 2}>
                      {alert.description}
                    </Text>
                  </View>
                  <Text style={styles.expandIcon}>{isExpanded ? "▲" : "▼"}</Text>
                </View>

                {/* Expanded Content */}
                {isExpanded && (
                  <View style={styles.expandedContent}>
                    <View style={styles.divider} />

                    <Text style={styles.expandedLabel}>What this means</Text>
                    <Text style={[styles.expandedText, { color: s.color }]}>
                      {alert.description}
                    </Text>

                    <View style={styles.actionBox}>
                      <Text style={styles.actionLabel}>⚕️ What to do</Text>
                      <Text style={styles.actionText}>
                        Do not stop or change your medications on your own.
                        Contact your healthcare provider or pharmacist as soon
                        as possible to discuss this interaction.
                      </Text>
                    </View>

                    <View style={styles.sourceRow}>
                      <Text style={styles.sourceText}>
                        Source: {alert.source || "AI agent"} · Not medical advice
                      </Text>
                    </View>
                  </View>
                )}
              </TouchableOpacity>
            );
          })}
        </>
      )}

      {/* Acknowledged Alerts */}
      {acknowledged.length > 0 && (
        <>
          <Text style={[styles.sectionTitle, { marginTop: 24 }]}>
            Previously reviewed
          </Text>
          {acknowledged.map((alert) => {
            const s = severityConfig[alert.severity] || severityConfig.minor;
            return (
              <View
                key={alert._id}
                style={[styles.alertCard, styles.alertCardDim, { borderColor: s.border }]}
              >
                <View style={styles.alertHeader}>
                  <Text style={[styles.alertIcon, { opacity: 0.5 }]}>{s.icon}</Text>
                  <View style={styles.alertHeaderText}>
                    <View style={styles.alertTitleRow}>
                      <View style={[styles.severityBadge, { backgroundColor: "#f3f4f6" }]}>
                        <Text style={[styles.severityBadgeText, { color: "#9ca3af" }]}>
                          {s.label} · Reviewed
                        </Text>
                      </View>
                    </View>
                    <Text style={styles.alertDescriptionDim} numberOfLines={2}>
                      {alert.description}
                    </Text>
                  </View>
                </View>
              </View>
            );
          })}
        </>
      )}

      <Text style={styles.footerText}>
        Always consult a qualified healthcare professional before making
        any changes to your medications.
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8f9fa" },
  content:   { padding: 20, paddingBottom: 100 },
  centered:  { flex: 1, alignItems: "center", justifyContent: "center" },

  pageTitle:    { fontSize: 22, fontWeight: "700", color: "#1a1a1a", marginTop: 48 },
  pageSubtitle: { fontSize: 13, color: "#9ca3af", marginTop: 2, marginBottom: 16 },

  emergencyBanner: {
    backgroundColor: "#fff1f2", borderRadius: 12,
    padding: 14, marginBottom: 12,
    borderWidth: 1, borderColor: "#fecdd3",
    flexDirection: "row", alignItems: "center", gap: 10,
  },
  emergencyText: { flex: 1, fontSize: 12, color: "#be123c", lineHeight: 17 },
  emergencyBtn: {
    backgroundColor: "#be123c", borderRadius: 8,
    paddingHorizontal: 12, paddingVertical: 6,
  },
  emergencyBtnText: { color: "#fff", fontSize: 11, fontWeight: "700" },

  disclaimer: {
    backgroundColor: "#eff6ff", borderRadius: 10,
    padding: 12, marginBottom: 20,
    borderWidth: 1, borderColor: "#bfdbfe",
  },
  disclaimerText: { fontSize: 11, color: "#1d4ed8", lineHeight: 16 },

  emptyBox: {
    backgroundColor: "#fff", borderRadius: 16,
    padding: 32, alignItems: "center",
    borderWidth: 1, borderColor: "#f3f4f6",
  },
  emptyEmoji: { fontSize: 40, marginBottom: 12 },
  emptyTitle: { fontSize: 15, fontWeight: "700", color: "#1a1a1a", marginBottom: 6 },
  emptyText:  { fontSize: 13, color: "#9ca3af", textAlign: "center", lineHeight: 18 },

  sectionHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 10 },
  sectionTitle:  { fontSize: 14, fontWeight: "700", color: "#1a1a1a" },
  countBadge: {
    backgroundColor: "#ef4444", borderRadius: 10,
    paddingHorizontal: 7, paddingVertical: 2,
  },
  countBadgeText: { color: "#fff", fontSize: 11, fontWeight: "700" },

  alertCard: {
    borderRadius: 14, padding: 14,
    marginBottom: 10, borderWidth: 1,
  },
  alertCardDim: { backgroundColor: "#fafafa", opacity: 0.7 },

  alertHeader:     { flexDirection: "row", gap: 10, alignItems: "flex-start" },
  alertIcon:       { fontSize: 20, marginTop: 2 },
  alertHeaderText: { flex: 1 },
  alertTitleRow:   { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 6 },
  alertDate:       { fontSize: 11, color: "#9ca3af" },

  severityBadge: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 20 },
  severityBadgeText: { fontSize: 11, fontWeight: "700" },

  alertDescription:    { fontSize: 13, lineHeight: 18, fontWeight: "500" },
  alertDescriptionDim: { fontSize: 12, color: "#9ca3af", lineHeight: 17 },
  expandIcon:          { fontSize: 12, color: "#9ca3af", paddingTop: 4 },

  expandedContent: { marginTop: 12 },
  divider:         { height: 1, backgroundColor: "rgba(0,0,0,0.06)", marginBottom: 12 },

  expandedLabel: { fontSize: 11, fontWeight: "700", color: "#6b7280", letterSpacing: 0.5, marginBottom: 6 },
  expandedText:  { fontSize: 13, lineHeight: 19, marginBottom: 12 },

  actionBox: {
    backgroundColor: "rgba(255,255,255,0.6)", borderRadius: 10,
    padding: 12, marginBottom: 10,
  },
  actionLabel: { fontSize: 12, fontWeight: "700", color: "#1a1a1a", marginBottom: 4 },
  actionText:  { fontSize: 12, color: "#4b5563", lineHeight: 18 },

  sourceRow: { alignItems: "flex-end" },
  sourceText: { fontSize: 10, color: "#9ca3af" },

  footerText: {
    fontSize: 11, color: "#d1d5db",
    textAlign: "center", marginTop: 20, lineHeight: 16,
  },
});